### PR TITLE
Publish 

### PR DESCRIPTION
**Pull request by huayunh**
#### Changes proposed in this Pull Request:
- Added 5 new icons
- make `@brightlayer-ui/icons-mui` compatible with MUI v5

### CODE REVIEW

**Review by emclaug2 — APPROVED** [review]

**Comment by jeffvg** [comment]
not sure but just checking....do we need to check in updated sprites? ```yarn sprites``` produced 55 file changes for me in Dev.

**Comment by huayunh** [comment]
I wasn't sure what `yarn sprites` does there; I noticed that it was part of the `yarn build` command so I didn't run it separately.

**Comment by daileytj** [comment]
@jeffvg @huayunh is there something we need to do about the sprite stuff? Or is this good to go?

**Comment by jeffvg** [comment]
> @jeffvg @huayunh is there something we need to do about the sprite stuff? Or is this good to go?

not sure. The build:font script hits the sprites and doesn't create anything new. But if you only run yarn sprites, you'll see the updates...

**Comment by jeffvg** [comment]
> @jeffvg @huayunh is there something we need to do about the sprite stuff? Or is this good to go?

seems to be only the path definition for optimized image but not sure

**Comment by emclaug2** [comment]
@huayunh I tried running `yarn sprites` and then looked at the diff between the new generated files; not sure what this is indicating.  This is an example of one of those changes:

Screen Shot 2022-03-29 at 2 45 43 PM

**Comment by huayunh** [comment]
See conversations in https://github.com/brightlayer-ui/icons/pull/198#issuecomment-1082248487

**Review by jeffvg — APPROVED** [review]

**Pull request merged**
