### PR TITLE
update definition paths

### PR DESCRIPTION
**Pull request by jeffvg**
Fixes # .

#### Changes proposed in this Pull Request:
- update sprite definition paths
- 
- 
The d attribute defines a path to be drawn

#### To Test:
- 
yarn && yarn sprites should not create updated sprites

### CODE REVIEW

**Comment by jeffvg** [comment]
was trying to do local commit and test this but wasn't working out, so opened branch for it

**Comment by huayunh** [comment]
now when I run yarn start, it undoes the output of `yarn sprites`...

**Comment by jeffvg** [comment]
> now when I run yarn start, it undoes the output of `yarn sprites`...

wow, so weird. Ok we can just close this PR

**Comment by jeffvg** [comment]
a yarn start trumps the sprites and returns the same file changes

**Pull request closed without merging**
