### PR TITLE
Build RN vector icons with RN 70

### PR DESCRIPTION
**Pull request by daileytj**
Fixes BLUI-3504.

#### Changes proposed in this Pull Request:
- Update to build RN vector icons with RN 70

#### To Test:
In one terminal
- `git clone git@github.com:brightlayer-ui/icons.git -b feature/3504-upgrade-to-rn-70`
- `cd icons/rn-vector`
-  `yarn pack`
-  yarn pack will generate a tarball file that you can use in place of the traditional `@brightlayer-ui/react-native-vector-icons` package, e.g., `/Users/E######/dev/brightlayer-ui/icons/rn-vector/brightlayer-ui-react-native-vector-icons-v1.8.0-beta.0.tgz`

In a second terminal
- `npx react-native init AwesomeTSProject2 --template react-native-template-typescript`
- add RNVI to the project using the tarball file. e.g.,`"@brightlayer-ui/react-native-vector-icons": "file:/Users/E######/dev/brightlayer-ui/icons/rn-vector/brightlayer-ui-react-native-vector-icons-v1.8.0-beta.0.tgz"
- Follow the rest of the RNVI integration as described here: https://github.com/brightlayer-ui/icons/blob/dev/rn-vector/README.md
- Add an icon or 2 to the view
- Be sure to test the project on android and iOS

### CODE REVIEW

**Comment by ektasawant** [comment]
Screenshot 2022-09-29 at 10 46 49 AM
Correct me if I am doing anything wrong  . `pod install` giving above error.

**Comment by daileytj** [comment]
@ektasawant the podfile should not point to the tarball file. Just point it to the node_modules as shown in the instructions link I provided in the test instructions.

`pod 'RNBLUIVectorIcons', :path => '../node_modules/@brightlayer-ui/react-native-vector-icons'`

**Comment by jeffvg** [comment]
all good on iOS but Android is another story

image

**Review by jeffvg — APPROVED** [review]
RN vector icons are working as intended via iOS. Assuming Android is good on your end

**Pull request merged**
